### ISSUE TITLE
Building Freetds on Windows with gnutls

### ISSUE THREAD

**Issue by cbolgiano** [FreeTDS/freetds#120]
We are unable to build freetds on windows with gnutls support.  We see that there is logic surrounding it but it looks like it is unreachable in the CMakeLists file.  What can we do using cmake to build freetds on windows with gnutls?

**Comment by freddy77** [comment]
Yes, not much supported. How do you compile and use GnuTLS on Windows? I don't think is hard to change code to use GnuTLS even on Windows but the CMakeLists.txt uses pkg_check_modules which maybe is not available on Windows.

**Comment by sfhacker** [comment]
Not sure whether or not this issue is related to this one here: http://lists.ibiblio.org/pipermail/freetds/2017q2/030175.html.
Anyway, I've read on several mailing lists that the **use of gnuTLS is strongly discouraged!**
Having said that, we have downloaded the latest version of gnuTLS and freeTDS (master branch).
We first built gnuTLS and later on freeTDS.
The output of tsql -C shows:

Compile-time settings (established with the "configure" script)
                            Version: freetds v1.1.dev.20170602
             freetds.conf directory: \\FreeTDS\\etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: auto
                              iODBC: no
                           unixodbc: yes (unixODBC 2.3.4)
              SSPI "trusted" logins: yes
                           Kerberos: no
                            OpenSSL: no
                             GnuTLS: yes (gnuTLS 3.5.12)
                               MARS: no

Please, contact us should you require (further) assistance.

P.S.: Try to avoid 'telegraphic' posts!

**Comment by freddy77** [comment]
John, how did you compiled GnuTLS and FreeTDS? It's weird that you seems to use Windows path but unixODBC. Did you compile for Windows or Unix? Which compiler did you use?
There were some notes about GnuTLS security on some mailing list but as far as I have found they are back to 2014.

**Comment by sfhacker** [comment]
Any update on this issue? It is nearly a month now!

We have successfully built the latest version of gnuTLS and the latest version of freeTDS.

**gnutls-serv** --version
gnutls-serv 3.5.12
Copyright (C) 2000-2017 Free Software Foundation, and others, all rights reserved.
This is free software. It is licensed for use, modification and
redistribution under the terms of the GNU General Public License,
version 3 or later <http://gnu.org/licenses/gpl.html>

Please send bug reports to:  <bugs@gnutls.org>


**gnutls-cli** --version
gnutls-cli 3.5.12
Copyright (C) 2000-2017 Free Software Foundation, and others, all rights reserved.
This is free software. It is licensed for use, modification and
redistribution under the terms of the GNU General Public License,
version 3 or later <http://gnu.org/licenses/gpl.html>

Please send bug reports to:  <bugs@gnutls.org>

**Comment by freddy77** [comment]
2017-06-08 22:28 GMT+01:00 John Sheppard <notifications@github.com>:

> Any update on this issue? It is nearly a month now!
>
> We have successfully built the latest version of gnuTLS and the latest
> version of freeTDS.
>
Sorry but these 2 lines are not that open source friendly... people should
contribute to the
project and not just expecting that the problems are fixed by some project
guy.
If you were able to fix the issue telling how you fixed it, being a full
good solution or
just a workaround is part of the way issue are handled.


> *gnutls-serv* --version
> gnutls-serv 3.5.12
> Copyright (C) 2000-2017 Free Software Foundation, and others, all rights
> reserved.
> This is free software. It is licensed for use, modification and
> redistribution under the terms of the GNU General Public License,
> version 3 or later http://gnu.org/licenses/gpl.html
>
> Please send bug reports to: bugs@gnutls.org
>
> *gnutls-cli* --version
> gnutls-cli 3.5.12
> Copyright (C) 2000-2017 Free Software Foundation, and others, all rights
> reserved.
> This is free software. It is licensed for use, modification and
> redistribution under the terms of the GNU General Public License,
> version 3 or later http://gnu.org/licenses/gpl.html
>
> Please send bug reports to: bugs@gnutls.org
>
Frediano

**Comment by cbolgiano** [comment]
I apologize for the lack of interaction with this issue I created.  The reason I opened this was to see if there was still support for gnutls when using cmake to get a freetds dll with gnutls instead of openSSL.  We were pressed for time and ended up just using openSSL.   http://lists.ibiblio.org/pipermail/freetds/2017q2/030175.html is related and I will close the issue to continue communication through the mailing list.  Thank you for the time spent and I apologize for the lack of follow up.
