### ISSUE TITLE
Support alternate libiodbc path

### ISSUE THREAD

**Issue by orlitzky** [FreeTDS/freetds#142]
In Gentoo, we store the iODBC headers in `/usr/include/iodbc`. FreeTDS doesn't give us an easy way to search there, since it appends `include/` to the path that you provide to `--with-iodbc`. To work around that, we patch `configure.ac` and regenerate all of the autotools files, and that involves a bunch of stuff we don't want to be doing =)

I can think of a few ways to support the alternate path. First, we could check both `$with_iodbc/include` and `$with_iodbc/include/iodbc` for the headers, and only fail if neither are present. This is simple and respects the user's `--with-iodbc` path, but also adds another special case.

Or, we could allow `--with-iodbc` to take "yes" as an argument (i.e. no argument). When `--with-iodbc` (or `--with-iodbc=yes`) is given, we could use pkg-config to get the include path,
```sh
$ pkg-config --cflags-only-I libiodbc
-I/usr/include/iodbc
```
Likewise, I can get the lib path and linker flags,
```sh
$ pkg-config --libs libiodbc
-liodbc -liodbcinst -ldl
$ pkg-config --libs-only-L libiodbc
 
```
The downside is that this would add another branch to the configure.ac (for `$with_iodbc = "yes"`), and it would require pkg-config as a build-time dependency.

What do you think?

**Comment by freddy77** [comment]
Make sense. I prefer to check first the more recent way (that is in this case pkg-config) so in this case if the value is yes I would use PKG_CHECK_MODULES(IODBC, iodbc, if_found, if_not_found) and use the defined variables (IODBC_CFLAGS, IODBC_LIBS) instead of calling pkg-config directly.
We already check for pkg-config and use automake macros, if pkg-config is not available is not a problem, configure will handle it as long as you don't call the executable directly (and configure also provides override of path and other feature).
Note that if --with-iodbc is not specified some lines below the iodbc block we try to detect the odbc type.
Not sure what should be the preference. I mean, if you specify --with-iodbc should try to use pkg-config and this is the easy path but if you specify --without-iodbc for instance you should not try to detect iodbc (and as far as I can see this is currently not the case). And in case of autodetect maybe we would like to use pkg-config if available, normal detect if not pkg-config fails and continue with others (unixODBC) if all methods fails.

**Comment by orlitzky** [comment]
Can I ask what's supposed to happen if the user enables more than one of `--with-iodbc`, `--with-unixodbc`, or `--with-odbc-nodm`?

**Comment by freddy77** [comment]
Merged patch that fix this issue.
