### ISSUE TITLE
Date and datetime formats

### ISSUE THREAD

**Issue by SergeyYavorsky** [FreeTDS/freetds#456]
The date formatting has been changed recently. Look, I have in my MS SQL table two fields, one of date type and another with datetime type. freetds-1.1.20 returned different formats for these fields. Like this:
```
1> SELECT TOP 2 [REPORT_DATE],[ESP_TRANSACTION_DATETIME] FROM [rs_live_161p].[dbo].[tF321P_4936U_Operation] where [ESP_TRANSACTION_DATETIME] is not null;
2> go
REPORT_DATE     ESP_TRANSACTION_DATETIME
2020-05-08      May  7 2020 05:15:15:000PM
2020-10-02      Oct  1 2020 08:37:17:000AM
```

And it was totally ok, considering we used freetds for postgres tds_fdw. But at least from version 1.3.3 and newer the date formatting became almost the same as datetime formatting, just without seconds fraction
```
1> SELECT TOP 2 [REPORT_DATE],[ESP_TRANSACTION_DATETIME] FROM [rs_live_161p].[dbo].[tF321P_4936U_Operation] where [ESP_TRANSACTION_DATETIME] is not null;
2> go
REPORT_DATE                   ESP_TRANSACTION_DATETIME
May  8 2020 12:00:00:AM       May  7 2020 05:15:15:000PM
Oct  2 2020 12:00:00:AM       Oct  1 2020 08:37:17:000AM
```

If I try to set date format in locales.conf file (date format = %Y-%m-%d) I end up with the same formatting for both fields and I lose time fraction of datetime field.

```
1> SELECT TOP 2 [REPORT_DATE],[ESP_TRANSACTION_DATETIME] FROM [rs_live_161p].[dbo].[tF321P_4936U_Operation] where [ESP_TRANSACTION_DATETIME] is not null;
2> go
REPORT_DATE     ESP_TRANSACTION_DATETIME
2020-05-08      2020-05-07
2020-10-02      2020-10-01
```

Is there any way to revert date formatting of new freetds versions to the previous behavior? Or is it possible to set formatting for date and datetime fields separately?

**Comment by BlackGrizzly** [comment]
There is no solution for this problem?

**Comment by fziglio** [comment]
Which library are you using? Which datatypes/precision?

**Comment by BlackGrizzly** [comment]
FreeTDS 1.3.6-1, MS SQL Server 2017. Datatypes: date and datetime. The problem started after upgrading to Ubuntu 22.04. On Ubuntu 21.10 there was a version of freetds 1.2.3-1build1 and there was no such problem

**Comment by fziglio** [comment]
FreeTDS provides 3 libraries, db-library, ct-library and ODBC. Which one are you using? Which tool did you use to issue your queries and get values back?

**Comment by BlackGrizzly** [comment]
ODBC, PHP 5.6, use php function mssql_query

**Comment by fziglio** [comment]
It would be useful to have a ODBC trace, see https://www.freetds.org/userguide/logging.html#Logging.odbc. Wondering who is doing the formatting. I suppose FreeTDS but better to check.

**Comment by JohnBryanDev** [comment]
I can reproduce this by switching TDS protocol version. ie on FreeTDS v1.3 (using CTLIB) and using "CS_TDS_70" (ie TDS V7.0) I see the "YYYY-MM-DD" behaviour. 

This appears to be because "date" fields are returned to the client as "text", eg (for a date of 1970-01-01)
`packet.c:410:Received packet
0000 04 01 00 45 00 33 01 00-81 01 00 00 00 08 00 e7 |...E.3.. ........|
0010 14 00 09 53 00 74 00 61-00 72 00 74 00 44 00 61 |...S.t.a .r.t.D.a|
0020 00 74 00 65 00 d1 14 00-31 00 39 00 37 00 30 00 |.t.e.... 1.9.7.0.|
0030 2d 00 30 00 31 00 2d 00-30 00 31 00 fd 10 00 c1 |-.0.1.-. 0.1.....|
0040 00 01 00 00 00         -                        |.....|`

and:
`token.c:1547:tds7_get_data_info:
        colname = StartDate
        type = 39 (varchar)
        server's type = 231 (x UCS-2 varchar)
        column_varint_size = 2
        column_size = 10 (20 on server)`

TDS protocol version 7.3 seems to have introduced native support for "date" and "time" fields, ie from:
[FreeTDS user guide link](https://www.freetds.org/userguide/ChoosingTdsProtocol.html#tab.Protocol.by.Product)

`TDS Version 7.3: Includes support for time, date, datetime2, datetimeoffset`

If I make the same request using "CS_TDS_70" (ie TDS V7.0), the value is returned from server in a binary format, and the client is reformatting it to "Jan  1 1970 12:00AM" (even though the "date" field doesn't CONTAIN a "time" portion).

ie:
`packet.c:410:Received packet
0000 04 01 00 37 00 9b 01 00-81 01 00 00 00 00 00 08 |...7.... ........|	
0010 00 28 09 53 00 74 00 61-00 72 00 74 00 44 00 61 |.(.S.t.a .r.t.D.a|
0020 00 74 00 65 00 d1 03 3a-f9 0a fd 10 00 c1 00 01 |.t.e...: ........|
0030 00 00 00 00 00 00 00   -                        |.......|`
and:
`token.c:1547:tds7_get_data_info:
        colname = StartDate
        type = 40 (date)
        server's type = 40 (date)
        column_varint_size = 1
        column_size = 16 (16 on server)`

"time" fields are similarly affected, (ie similarly were returned as "text" from SQL Server when using TDS v7.0 (etc) protocol version, returned as "binary" with FreeTDS library doing the conversion when using TDS v7.4 protocol).

Issues here are:
- The format that SQL Server returned is *different* from the format FreeTDS generates.
- The format FreeTDS generates contains a spurious "date" portion for "time" type fields, and a spurious "time" portion for "date" type fields.

Issue also seen here: https://stackoverflow.com/questions/70739826/microsoft-sql-server-freetds-and-formatting-of-legacy-datetime-type

**Comment by freddy77** [comment]
Mumble... the format string for dates/times can be changed, see https://www.freetds.org/userguide/locales.html. For historical and compatibility the format is more "English" than ISO so it's different. About date and time (not timestamp/datetime like in the sense that there are either date or time but not both) this is another issue. At the moment all dates/times/datetimes use a single formatting string. Specifically I think at code in src/tds/convert.c, https://github.com/FreeTDS/freetds/blob/feefa9d2e28a620a86bcb2bdab5061b8ca78fdcb/src/tds/convert.c#L1287.

**Comment by freddy77** [comment]
Added in 1.3.20 `date-only format` and `time-only format` to `locales.conf`, see https://www.freetds.org/userguide/locales.html.
