### ISSUE TITLE
tdspool segfault

### ISSUE THREAD

**Issue by vstaf** [FreeTDS/freetds#73]
Hello @freddy77 !
I've got another bug with tdspool :) it crash periodicaly. You can find core-dump and tdspool binary in the attachment.
[tdspool_segfault.zip](https://github.com/FreeTDS/freetds/files/399359/tdspool_segfault.zip)

Hope this helps for understanding the problem.
V.

**Comment by freddy77** [comment]
Pretty hard to understand, not much debugging information.
It's crashing in a SSL_connect call from tds_ssl_init.
Unfortunately I don't have the /usr/lib/libssl.so.10 and /usr/lib/libcrypto.so.10 files to get the right function where is crashing. Can you send me these libraries too?
Can you try and use GnuTLS instead of OpenSSL?
You are using RedHat/CentOS 6, right?

**Comment by vstaf** [comment]
Yep, CentOS 6 x86
openssl-1.0.1e-16.el6_5.1.i686

[libs.zip](https://github.com/FreeTDS/freetds/files/401493/libs.zip)

**Comment by freddy77** [comment]
Mumble... got the stack

crash in sha1_block_data_order 

0x005c8d03 SHA1_Update
0xae7fbcf8 ebp
0xae7fbcbc esp

0x00646e7f ???
0xae7fbd18 ebp

0x0063e3d4 EVP_DigestUpdate
0xae7fbd38 ebp at 0x0063e3d4
0xae7fbd20 esp

0x0063a275 ???
0xae7fbdf8 ebp
0xae7fbd40 esp

0x0063ad0e RAND_pseudo_bytes
0xae7fbe18 ebp
0xae7fbe00 esp

0x00b8de8f ssl3_client_hello
0xae7fbe78 ebp
0xae7fbe20 esp

0x00b8fe27 ssl3_connect
0xae7fbed8 ebp
0xae7fbe80 esp

0x00bad15b SSL_connect
0xae7fbef8 ebp
0xae7fbee0 esp

0x08069b69 tds_ssl_init
0xae7fbf88 ebp
0xae7fbf00 esp

The crash is an instruction pointing to not existing page (some bytes before is valid). I don't think there is a buffer overflow in sha code.

Looking at the thread
(gdb) info threads 
  Id   Target Id         Frame 
* 1    LWP 28837         0x005cb8ce in ?? () from ./usr/lib/libcrypto.so.10
  2    LWP 28826         0x005c8bcc in SHA1_Update () from ./usr/lib/libcrypto.so.10
  3    LWP 28827         0x005fef40 in bn_mul_mont () from ./usr/lib/libcrypto.so.10
  4    LWP 28832         0x00638e08 in ?? () from ./usr/lib/libcrypto.so.10
  5    LWP 28835         0x00f0f424 in __kernel_vsyscall ()
  6    LWP 28838         0x005c3032 in FIPS_mode () from ./usr/lib/libcrypto.so.10
  7    LWP 28822         0x00f0f424 in __kernel_vsyscall ()
  8    LWP 12049         0x00f0f424 in __kernel_vsyscall ()
  9    LWP 28840         0x00f0f424 in __kernel_vsyscall ()
  10   LWP 28833         0x00f0f424 in __kernel_vsyscall ()
  11   LWP 28830         0x005fef40 in bn_mul_mont () from ./usr/lib/libcrypto.so.10

So my thread and another are using sha code. Beside the question why all this threads and why all these threads using OpenSSL at the same time I think you are having a thread problem with OpenSSL. It's actually strange that there as so much thread using OpenSSL, this should be used just to connect and that unencrypted data should be used in the pool so... it's the pooling working? I suspect so by your tests by the way. Could be this happens when a server is restarted?

If you can try GnuTLS, I'll try to write a possible patch.

**Comment by freddy77** [comment]
Can you try this patch?
https://github.com/freddy77/freetds/commit/b481ff09d0a399a3d1d7b96042549c6e33bf2e3b

**Comment by vstaf** [comment]
I updated openssl to the latest version from centos repo and now segfaults gone (3 days without segfaults), need more time to monitoring. If i got new crashes, i'll try your patch

**Comment by vstaf** [comment]
I'm closing the issue, there is no segfaults since i've update openssl. Thanks for your time!
