### ISSUE TITLE
Incorrect work of JOIN clause

### ISSUE THREAD

**Issue by rentechpro** [FreeTDS/freetds#91]
create foreign table ms_tables (
tab_name varchar(128),
col_name varchar(128),
typ_name varchar(128),
len smallint
)
server fs_rc
options (query '
select so.name as tab_name, sc.name as col_name, st.name as typ_name, sc.length as len
from sysobjects so
join syscolumns sc on sc.id = so.id
join systypes st on st.xtype = sc.xtype
where so.xtype = ''U''
order by so.name, sc.colid;
');

select count (1) from ms_tables; -- 109 rows

select count (1) -- 16 rows
from information_schema.tables t
where table_schema = 'dbo'
and table_type = 'BASE TABLE';

select count (1) -- 12 rows
from information_schema.tables t
join ms_tables m on lower (m.tab_name) = lower (t.table_name)
where table_schema = 'dbo'
and table_type = 'BASE TABLE';

select count (1) -- 103 rows
from information_schema.tables t
full join ms_tables m on lower (m.tab_name) = lower (t.table_name)
where table_schema = 'dbo'
and table_type = 'BASE TABLE';

The schema dbo has 16 same table names on both sides. but join see 1 the same table name only!

The full join sees all 16 table names but simple join see the same quantity.

Postgres 9.6.1, tds_fdw-1.0.8, MS SQL 2008R2.

**Comment by freddy77** [comment]
What you are doing is quite complicated and needs some more explanation.
If I understood you are using some mssql tables attached to a Postgres database. Is not clear where you run each query, what are the expected results and why.

**Comment by rentechpro** [comment]
There are some tables on MS SQL which are used as foreign tables in PG SQL.
Also there are some usual tables with the same structure in PG SQL.
All queries listed above have been executed on Postgres 9.6.1 with the help of PGAdmin 4.1.1.
The query
    select count (1) -- 12 rows
    from information_schema.tables t
    join ms_tables m on lower (m.tab_name) = lower (t.table_name)
    where table_schema = 'dbo'
        and table_type = 'BASE TABLE';
expects the result of 103 rows (each table_name in schema which complete list of column names.

**Comment by freddy77** [comment]
There are too many layer to understand.
FreeTDS has good loggings. They are enabled using environments or options.
You can find how to enable these dumps at http://www.freetds.org/userguide/logging.htm and http://www.freetds.org/userguide/freetdsconf.htm.
The logs can be quite verbose so don't use on production and do small queries.
This will help understand the query PG + tds_fdw are sending and how they retrieve data from mssql.
I would personally try also to use an ODBC bridge instead. DB-Library has its limit although our implementation have some extensions.

**Comment by mckaygerhard** [comment]
the problem here are in two layer interaction, due i have similar environment in sybase using proxy tables..

i'll clarify her that in sybase proxy tables rely complety in the odbc connection, and in this case of PG+mocosoft there using a library event odbc.. db library its quite complicated to develop and resolv, due there's two artifacts : the implementation does by the application that use the library (are good) and the usage integration of the library itself

so @freddy77 has right and i added that in good sense: with the previous clarification here its not clear where are happening the problem, in the library or in the implementation of the library.. so i thing its better use the odbc brigde..

the mocosoft does not are famous by follow standars, contrary, by breaks all of them... at leas sybase using the proxy tables for something like @rentechpro try to do, are made complety in the sybase environment rely on the odbc connection so the problem are always in one direction the odbc connection

**Comment by freddy77** [comment]
Closing, was expecting some logs.
